markdown: kramdown
kramdown:
  input: GFM
highlighter: true
permalink: /:year/:month/:title
include: ['.htaccess']
exclude: ['node_modules', 'scss', 'Gruntfile.js', 'package.json', '*.sublime-project', '*.sublime-workspace', 'index-static.php', 'index-handlebars.php', 'blog-src', 'js-old']
timezone: Europe/London

paginate: 25
paginate_path: /page:num

# Vars
name: Zander Martineau
myname: Zander Martineau
email: zander@martineau.tv
socialusername: MrMartineau

collections:
 - work

# defaults:
#   -
#     scope:
#       path: "" # empty string for all files
#     values:
#       layout: "post"
#   -
#     scope:
#       path: "work"
#       type: "post"
#     values:
#       layout: "work"
