permalink: /:year/:month/:title/
include: ['.htaccess']
exclude: ['node_modules', 'scss', 'Gruntfile.js', 'package.json', '*.sublime-project', '*.sublime-workspace', '*.sketch', 'bower_components', 'README.md', 'bower.json']
timezone: Europe/London
excerpt_separator: ""

# Vars
name: Z&er
myname: Zander Martineau
email: zander@martineau.tv
socialusername: MrMartineau
bio: "I'm Zander, a senior front-end developer from London. I work at [TMW](//tmwunlimited.com) as a Creative Technology Lead, when I'm not working there I can usually be found hacking on [Kickoff](//trykickoff.com) or [other open source projects](//github.com/mrmartineau). Read [some articles](/#articles) or get in contact with me in any of the usual ways; it'd be great to hear from you."
metadescription: "I'm Zander, a front-end developer from London. I work at TMW as a Creative Technology Lead. When I'm not working there I can usually be found hacking on Kickoff or other open source projects."
url: http://martineau.tv

collections:
  work:
    output: true
    permalink: /work/:path/
  lab:
    output: true
    permalink: /lab/:path/
  code:
    output: true
    permalink: /code/:path/

defaults:
  - scope:
      path: "work"
    values:
      layout: "work"
