markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: /:year/:month/:title
include: ['.htaccess']
exclude: ['node_modules', 'scss', 'Gruntfile.js', 'package.json', '*.sublime-project', '*.sublime-workspace', '*.sketch', 'bower_components', 'README.md', 'bower.json']
timezone: Europe/London

# Vars
name: Zander Martineau
myname: Zander Martineau
email: zander@martineau.tv
socialusername: MrMartineau

collections:
  work:
    output: false
  lab:
    output: true
    permalink: /lab/:path/

# defaults:
#   -
#     scope:
#       path: "" # empty string for all files
#     values:
#       layout: "post"
#   -
#     scope:
#       path: "work"
#       type: "post"
#     values:
#       layout: "work"
