permalink: /:year/:month/:title/
include: ['.htaccess']
exclude: ['node_modules', 'scss', 'Gruntfile.js', 'package.json', '*.sublime-project', '*.sublime-workspace', '*.sketch', 'bower_components', 'README.md', 'bower.json']
timezone: Europe/London
gems: ['emoji']
emoji_dir: /img/emoji

# Vars
name: Z&er
myname: Zander Martineau
email: zander@martineau.tv
socialusername: MrMartineau

collections:
  work:
    output: true
    permalink: /work/:path/
  lab:
    output: true
    permalink: /lab/:path/
  code:
    output: true
    permalink: /code/:path/

defaults:
  -
    scope:
      path: "work"
    values:
      layout: "work"
